spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db
    username: user
    password: password
  sql:
    init:
      encoding: UTF-8

server:
  servlet:
    session:
      timeout: 30m # spring bootのデフォルト値（30分）
